name: CI
on:
  push:
    branches:
      - main
env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout # 步骤1
        uses: actions/checkout@v3 # 使用的动作。格式：userName/repoName。作用：检出仓库，获取源码。 官方actions库：https://github.com/actions
      - name: Use Node.js 16 # 步骤2
        uses: actions/setup-node@v3 # 作用：安装nodejs
        with:
          node-version: 16 # 版本
      - name: CI
        run: npm ci && npm run build
      - name: CD
        run: npm publish